[package]
name = "server"
version = "0.1.0"
authors = ["Oleg Gashev <oleg@gashev.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1"
grpcio = "0.4"
protobuf = { version = "2", features = ["with-bytes"] }